### PR TITLE
fix(graph-networks-indexer): set replicas for indexer-service

### PR DESCRIPTION
**Pull request by MattKetmo**
Hello,

There was an incorrect copy-paste from the indexer-agent (StatefulSet) to the indexer-service (Deployment), which prevented setting more than 1 replica for the service.

### CODE REVIEW

**Comment by cjorge-graphops** [comment]
@MattKetmo thank you! we're delighted by your contribution :smile:

this looks great, could you be bothered to take the chance and just add a comment line above the replicas parameter on the `values.yaml` file?

something like: "  # -- Number of replicas to run"
or if not, we can add that later as well.

(point of it being to end up in the generated docs describing the purpose of that parameter)

**Review by cjorge-graphops — APPROVED** [review]

**Comment by cjorge-graphops** [comment]
@MattKetmo approved :) feel free to go ahead and merge!

**Comment by MattKetmo** [comment]
@cjorge-graphops I don't have the right to merge on this repo 😅

**Comment by cjorge-graphops** [comment]
@MattKetmo ups, sorry about that, merged and released. Thank you!

**Pull request merged**
